# Generated by Django 5.1.3 on 2025-10-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spalod_app', '0002_flyvastpointcloud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_iri', models.CharField(max_length=500)),
                ('original_uri', models.CharField(max_length=500)),
                ('new_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('new_uri__isnull', True), ('new_uri__startswith', 'http'), _connector='OR'), name='vocab_new_uri_http_or_null')],
                'unique_together': {('user', 'dataset_iri', 'original_uri')},
            },
        ),
    ]
